Update __init__.py
Fixes the following import issue related to importing iplot_error_map / iplot_gate_map from qiskit.providers.ibmq.visualization.interactive.error_map / gate_map. 

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [4], in <cell line: 1>()
----> 1 from qiskit.providers.ibmq.visualization.interactive.error_map import iplot_error_map

File ~/.local/lib/python3.10/site-packages/qiskit/providers/ibmq/visualization/__init__.py:36, in <module>
      1 # This code is part of Qiskit.
      2 #
      3 # (C) Copyright IBM 2018, 2020.
   (...)
     10 # copyright notice, and modified files need to carry a notice indicating
     11 # that they have been altered from the originals.
     13 """
     14 ===========================================================
     15 Visualizations (:mod:`qiskit.providers.ibmq.visualization`)
   (...)
     33    iplot_error_map
     34 """
---> 36 from .interactive import iplot_error_map, iplot_gate_map

ImportError: cannot import name 'iplot_error_map' from 'qiskit.providers.ibmq.visualization.interactive' (/home/user/.local/lib/python3.10/site-packages/qiskit/providers/ibmq/visualization/interactive/__init__.py)